global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # User Service
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'user-service'
          service: 'user-service'
          environment: 'development'

  # Chat Service
  - job_name: 'chat-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          application: 'chat-service'
          service: 'chat-service'
          environment: 'development'

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']