spring:
  application:
    name: user-service
  
  config:
    import: 
      - classpath:config/db-dev.yml
      - classpath:config/redis-dev.yml
      - classpath:config/kafka-dev.yml
      - classpath:config/mail-dev.yml
      - classpath:config/external_api_service-dev.yml
      - classpath:config/eureka-dev.yml
      - classpath:config/jwt_secret-dev.yml
      - classpath:config/encryption_secret-dev.yml

# Server Configuration
server:
  port: 8080

